### ISSUE TITLE
`translatesAutoresizingMaskIntoConstraints = false` should be part of library

### ISSUE THREAD

**Issue by asadali737** [roberthein/TinyConstraints#19]
`translatesAutoresizingMaskIntoConstraints = false` should be part of library. 
Currently we need to set this manually. Which sometimes most of the developers forget to do. Whenever a user wants to add constraint this should be set to `false` automatically.

**Comment by roberthein** [comment]
Thanks @asadali737! I will add this is asap 👍

**Comment by roberthein** [comment]
I just released **TinyConstraints 2.1.0** which takes care of setting `translatesAutoresizingMaskIntoConstraints` to `false`.
