### ISSUE TITLE
Adding support to ignore the Ascender/Descender in views that display text

### ISSUE THREAD

**Issue by GoldenJoe** [roberthein/TinyConstraints#20]
Not really sure how you would like to implement this in the main project, but I wrote an extension that allows you to easily align the top and bottom edges of UILabel and UITextView so that they line up visually with the top/bottom of the text instead of being off a little due to ascender/descender.

https://pastebin.com/hYum9uLf

**Comment by roberthein** [comment]
I really like your solution for this problem, very smart. 💯
But I think it is too specific to include in the framework.

**Comment by GoldenJoe** [comment]
Fair enough. Mind if I use your framework as a base for my own version? I like most of what you have going on.

**Comment by roberthein** [comment]
It's a free world! 🤘 You can use whatever code you find in **TinyConstraints** as you see fit.
Though I would appreciate it a lot if you keep sharing good ideas about the subject 😉
