### ISSUE TITLE
Feature request: stack views of different size

### ISSUE THREAD

**Issue by gerchicov-bp** [roberthein/TinyConstraints#21]
In my case I have 3 views placed in vertical order. The problem is it is enough hard to setup them because the are all different but must fill the whole space given to them with predefined height proportion.

**Comment by roberthein** [comment]
Hi @gerchicov-bp! If you could post the code here so I can better understand the problem and help you with the solution :)

**Comment by gerchicov-bp** [comment]
https://i.stack.imgur.com/ABfHe.png
All the views have constraints: to the left and to the right of superview, to the nearest top and nearest bottom border (sibling or parent). Each view also has a constraint "height=some_number*superview.height".

The result - views save height proportions independently from size and in the same time they fulfill superview.

**Comment by roberthein** [comment]
If I understand the problem correctly, this is what you want:
https://github.com/roberthein/TinyConstraints/blob/master/Example/TinyConstraints/Examples/Advanced.swift#L41
Here I set `relation: .equalOrLess` for the last constraint in the stack. 

Let me know if this fixes your issue. If not please share the code..

**Comment by gerchicov-bp** [comment]
NO. In all of your examples the inner views have equal width and height. What if I need for example a stack of views of sizes:
```
a*b
a*2b
a*3b
```

where ```a == superview.width``` and ```b + 2b + 3b = superview.height```

**Comment by roberthein** [comment]
@gerchicov-bp Check. You want for example:
`superview.height(200)`
`view1.height(to: superview, multiplier: 1/3)`
`view2.height(to: superview, multiplier: 1/3)`
`view3.height(to: superview, multiplier: 1/3)`
Right?

`multiplier` is not implemented at this point, but I could add it this week if this is what you need.

**Comment by gerchicov-bp** [comment]
If you didn't implement it then I advice you not to do that - if you add constraints inside such views their behaviour becomes unpredictable. Maybe this occurs because of numbers which become decimal

**Comment by roberthein** [comment]
I will try to implement this feature while avoiding unpredictable behaviour and let you know here when I did it.

**Comment by roberthein** [comment]
I just released TinyConstraints 2.1.0 with the `multiplier` property.
