### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by Andriyas123** [roberthein/TinyConstraints#22]
Hello!

I could not find another way of contacting you so I had to create an issue... I just have a quick newbie question:

How do I, for example, set top and bottom alignment of a button to another button? It seems to be quite easy in IB, but whenever I say, for example `button.top (to: anotherButton)`, Xcode crashes with finding nil while unwrapping an optional value. 

I add those constraints to UIButton after I added it into my subview. I know I am missing something out but I cannot quite get what. Here is an example of my code:

        cancelButton = UIButton(frame: CGRect(x: 10.0, y: 10.0, width: 50.0, height: 50.0))
        cancelButton.layer.shadowOpacity = 0.7
        cancelButton.layer.shadowOffset = CGSize(width: 0.0, height: 0.0)
        cancelButton.layer.shadowRadius = 5.0
        cancelButton.showsTouchWhenHighlighted = true
        cancelButton.setImage(#imageLiteral(resourceName: "Close"), for: UIControlState())
        cancelButton.addTarget(self, action: #selector(cancel), for: .touchUpInside)
        view.addSubview(cancelButton)

        cancelButton.height(50)
        cancelButton.width(50)
        cancelButton.leading(to: saveButton)
        
        saveButton = UIButton (frame: CGRect(x: 10.0, y: 506.0, width: 50, height: 50))
        saveButton.layer.shadowOpacity = 0.7
        saveButton.layer.shadowOffset = CGSize(width: 0.0, height: 0.0)
        saveButton.layer.shadowRadius = 5.0
        saveButton.showsTouchWhenHighlighted = true
        saveButton.setImage(#imageLiteral(resourceName: "Save"), for: UIControlState())
        saveButton.addTarget(self, action: #selector(save), for: .touchUpInside)
        view.addSubview(saveButton)
        
        saveButton.height(50)
        saveButton.width(50)
        saveButton.edges(to: cancelButton)`

**Comment by roberthein** [comment]
Hi @Andriyas123!

This is the problem: `cancelButton.leading(to: saveButton)`
The problem here is that you did add `cancelButton` as a subview of `view` but `saveButton` is not yet added to a superview at this point.

Let me know if this fixes your problem :)

**Comment by roberthein** [comment]
@Andriyas123 There are some other issues too:
- For every view you want to use with Auto Layout you have to set `translatesAutoresizingMaskIntoConstraints` to `false`.
- For every view you want to use with Auto Layout you do not initialise the view with a frame, you can use `UIView()` or `UIView(frame: .zero)` instead.
- There is also a redundancy: for `cancelButton` you set the `leading` edge to `saveButton` and for `saveButton` you set all edges including `leading` to `cancelButton`.

**Comment by roberthein** [comment]
@Andriyas123 What is the layout you want to achieve here? Maybe I can help you with the setup.

**Comment by Andriyas123** [comment]
@roberthein First of all, thank you for your explanation. It now makes more sense to me. 

Secondly, I attach a screenshot of the first VC where constraints to all buttons have been applied in IB. (It is a Camera Preview VC, thus when user takes a photo, he is redirected to another VC that I set up programatically. It is represented by the second screenshot.) 

For example, I need Pencil Button to be in top right corner all of the time, while Save Button in lower left. When I run it on my iPhone 5, it is fine, but of course, when I attach iPhone 6 Plus, for instance, buttons in my second VC are completely messed up for understandable reasons. 

That's what I want to achieve, basically. I hope I explained it well... Once again, @roberthein, thank you for your help!

![1 vc all is fine](https://cloud.githubusercontent.com/assets/21131181/25139820/61582dc6-242c-11e7-8433-fc0ed11946fc.png)
![2 vc problems here](https://cloud.githubusercontent.com/assets/21131181/25139821/6161fe78-242c-11e7-94ed-8a0797a3d069.png)

**Comment by roberthein** [comment]
First make sure you are using **TinyConstraints 2.0**
Initialise every button with `UIButton()`, no frames.
For every button add `button.translatesAutoresizingMaskIntoConstraints = false`

Then, after you created and added all the buttons, write this:

```
        let margin: CGFloat = 10
        let buttonSize = CGSize(width: 50, height: 50)
        let largeButtonSize = CGSize(width: 60, height: 60)
        
        cancelButton.size(buttonSize)
        cancelButton.top(to: view, offset: margin)
        cancelButton.left(to: view, offset: margin)
        
        saveButton.size(buttonSize)
        saveButton.bottom(to: view, offset: -margin)
        saveButton.left(to: view, offset: margin)
        
        shareButton.size(largeButtonSize)
        shareButton.bottom(to: view, offset: -margin)
        shareButton.right(to: view, offset: -margin)
        
        drawButton.size(buttonSize)
        drawButton.top(to: view, offset: margin)
        drawButton.right(to: view, offset: -margin)
        
        textButton.size(buttonSize)
        textButton.top(to: view, offset: margin)
        textButton.rightToLeft(of: drawButton, offset: -margin)
```

I hope this will help you on your way, but don't hesitate if you if more questions.

**Comment by Andriyas123** [comment]
@roberthein Thank you! I have added the code, it works smoothly but need to try it on a different device later. 

I will answer with my progress and will let you close this 'issue' ASAP. Thank you!

**Comment by roberthein** [comment]
🤘

**Comment by Andriyas123** [comment]
@roberthein Constraints work! You are a genius, thank you! This 'issue' can be closed.

**Comment by roberthein** [comment]
No problem! Success!
