### ISSUE TITLE
Weird temp error in Xcode 9 b5

### ISSUE THREAD

**Issue by radianttap** [roberthein/TinyConstraints#29]
If you are getting this:

```
TinyConstraints/Classes/Constraints.swift:40:33: 
Raw type 'LayoutPriority' (aka 'UILayoutPriority') is not expressible by any literal
```

on 

```
public enum ConstraintPriority: LayoutPriority
```

then make sure your TinyConstraints CocoaPods target is marked to use Swift 3.2 and not Swift 4 which is default (SWIFT_VERSION in build settings).

I want my hour back. 😒

**Comment by roberthein** [comment]
Aah sorry man, if I could give you your hour back, I would.
I'll make an update tonight. ✌️

**Comment by radianttap** [comment]
Ah, it's all fine. Just wanted to help anyone else that my encounter this problem

**Comment by roberthein** [comment]
I made a new branch with upcoming changes for **Swift 4**, you can check it out here:
https://github.com/roberthein/TinyConstraints/tree/release/swift-4
