### ISSUE TITLE
Not compatible with app extensions

### ISSUE THREAD

**Issue by basememara** [roberthein/TinyConstraints#52]
Thanks for a great library!

I can't use TinyConstraints in my Today Widget. Can you please enable `Allow app extension API only`? I tried this and the target still compiled successfully.

![screenshot 2018-03-15 at 12 45 34 pm](https://user-images.githubusercontent.com/892152/37477836-0e6b1a42-284f-11e8-9caf-8ce91cd9e996.png)

**Comment by basememara** [comment]
See PR #53

**Comment by roberthein** [comment]
Should be fixed now in 3.2.0. ✌️
