### ISSUE TITLE
Improve code completion for constraints that need offsets and insets

### ISSUE THREAD

**Issue by mennolovink** [roberthein/TinyConstraints#56]
TinyConstraints is using a lot of methods with default parameters, unfortunately Xcode's code completion follows an all or nothing approach; it either shows the method with all the default parameters, or the method without any defaults, not the in between ones. 

**Current behavior**
Because of this, creating a constraint that needs an offset is a bit tedious:
![current code completion](https://user-images.githubusercontent.com/2656075/40588420-6776d3de-61dd-11e8-922c-96b7fc90ef0a.gif)

**Desired behavior**
It would be nice and faster if there would be code completions available that include the offsets and insets:
![preferred code completion](https://user-images.githubusercontent.com/2656075/40588434-830d2260-61dd-11e8-9874-d6684f9eb882.gif)

**How to approach this**
To make sure, the right code completions become available, you'd have to add some convenience methods for the completions you'd like to support. I've been doing this extensively for the public api of [Zoomy](https://github.com/mennolovink/Zoomy).

**Comment by mennolovink** [comment]
@roberthein:  I've added a [Pullrequest](https://github.com/roberthein/TinyConstraints/pull/57) this look forward to hearing about this :)

**Comment by mennolovink** [comment]
Xcode 10 is supposed to have improvements with code completion. It might touch this subject as well, but I don't know this for sure. I'll run TC with Xcode 10 this week to see if the PR is still relevant.

**Comment by roberthein** [comment]
Awesome! Thanks!

**Comment by mennolovink** [comment]
Ok, So I just fired up Xcode 10 to see to what extend the code completion has changed. And I can confirm, that this issue is still relevant in Xcode 10.

Here's the options you currently get get for `leftToSuperView`:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/2656075/40990884-77bf7874-68f2-11e8-8244-a2a1881045e6.png">

when using my PR:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/2656075/40991177-38a18cc6-68f3-11e8-852b-41d83a4944e3.png">

On a side note, Xcode 10 comes with Swift 4.2. Tiny constraints currently does not compile in Swift 4.2. I'll create an issue for this 👌.

**Comment by roberthein** [comment]
Decided that this is not the best way to tackle this issue.
