### ISSUE TITLE
Doesn't compile in Swift 4.2

### ISSUE THREAD

**Issue by mennolovink** [roberthein/TinyConstraints#58]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/2656075/40991509-469bce76-68f4-11e8-9978-1fbc4bf80487.png">

I might find some time to implement the needed changes for this, but not sure yet.

**Comment by timedwardsios** [comment]
PR open https://github.com/roberthein/TinyConstraints/pull/63

**Comment by roberthein** [comment]
There is a Swift 4.2 brach now. 👌
`pod 'TinyConstraints', :git => 'https://github.com/roberthein/TinyConstraints.git', :branch => 'release/Swift-4.2'`
