### ISSUE TITLE
Weird effect when Right to left 

### ISSUE THREAD

**Issue by remaerd** [roberthein/TinyConstraints#59]
I was trying to support Right to left languages in my app after studying a localisation session from WWDC 18. I had troubles on Trailing Constraints with TinyConstraints. I thought it was an error caused by iOS 12, But it turns out I was wrong.

After switching back to UIKit's TrailingAnchor instead of TinyConstraints's related API. It's work out fine. I noticed that TinyConstraints helped my inverts some math of AutoLayout by default. But it looks like it doesn't work with Right to left languages.

Any thoughts on this issue? Thanks.

**Comment by roberthein** [comment]
Yes this was wrong, should be fixed now in 3.2.0. ✌️
