### ISSUE TITLE
Naming - Expectation Clashes

### ISSUE THREAD

**Issue by SuperWomble** [roberthein/TinyConstraints#6]
This looks like a very useful project!

However, the naming of some of the methods -- particularly those normally relating to dimensions -- will cause some confusion

For this reason, I suggest renaming to something like:

```
view.heightConstraint
view.widthConstraint 
view.sizeConstraint
view.centerConstraint
etc.
```
or

```
view.constrainWidth
view.constraintHeight
view.constrainSize
view.constrainCenter
etc.
```

The slight increase in verbosity would do a lot to help understanding and recall, without going all over-verbose overkill like the current Auto Layout API.

Cheers. And thank you for your contribution.

**Comment by roberthein** [comment]
I considered something like this when I wrote these functions and came to conclusion that I like the shorter version more. Maybe I change my mind later ;)

**Comment by muescha** [comment]
other suggestion:

```
view.constrain.width
view.constraint.height
view.constrain.size
view.constrain.center
etc.
```
