### ISSUE TITLE
Naming suggestion...

### ISSUE THREAD

**Issue by patniemeyer** [roberthein/TinyConstraints#64]
I like TinyConstraints but the naming makes it a little awkward to discover the methods by stumbling through syntax completion... For an extension like this maybe consider having all of these methods start with a verb prefix like "constrain" or "anchor"?   Just a suggestion.  Thanks.

**Comment by MarcSteven** [comment]
@patniemeyer great ,good tips to do it

**Comment by patniemeyer** [comment]
To help your users make the transition you could duplicate the methods and deprecate the old ones for a few releases.

**Comment by roberthein** [comment]
I get your suggestion, thought a lot about this in the beginning, but it would make TinyConstraints a little less tiny and a little more tedious to write. 
Maybe we can think of another way that makes it easier to discover the methods @patniemeyer @MarcSteven?
