### ISSUE TITLE
YouTube video tutorials

### ISSUE THREAD

**Issue by rebeloper** [roberthein/TinyConstraints#70]
Hi,

I am using TimyConstraints in several of my and my clients apps. I just absolutely love it.

So I decided to create two YouTube videos tutorials that take a hands on approach in explaining how to use TinyConstraints.

You can take a look at it here: https://www.youtube.com/playlist?list=PL_csAAO9PQ8ZDbGk57RlBRnNpxBGBAEOc

If you like it consider adding it to the README. And because an image can say a thousand words you could use this screenshot: 
<img width="1304" alt="screenshot 2018-12-12 at 23 44 23" src="https://user-images.githubusercontent.com/2488011/49900704-02b0df80-fe68-11e8-85f5-a7c42033592a.png">

Thank you for your hard and continued work on TinyConstraints!

**Comment by roberthein** [comment]
Thank you so much @rebeloper for this exposure and sorry for my late reply, but I added it now to the readme. ❤️
