### ISSUE TITLE
TinyConstraints cannot run on simulator

### ISSUE THREAD

**Issue by George-J-E** [roberthein/TinyConstraints#77]
I am unable to run my app in the simulator, even though it works fine for a device with ARM architecture.

Xcode gives this error for simulators:

> Could not find module 'TinyConstraints' for architecture 'x86_64'; found: arm64, arm, armv7

**Comment by CoreyCole** [comment]
Maybe trying cleaning and rebuilding?

**Comment by eliburke** [comment]
See #101 / #102 for a solution.
