### ISSUE TITLE
Possibility of Joining Forces

### ISSUE THREAD

**Issue by cyphactor** [roberthein/TinyConstraints#8]
Hey all,

I have been working on a similar constraints library currently called `Constraid` your friendly constraints aid. We have the same ideals/goals as this project but are a little further along.

We are definitely early on so are willing shift and adjust the naming of the methods in the API as we come up with better terminology for representing these concepts. Anyways, we have evolved this library after using it in a number of apps.

Was wondering if you would be interested in possibly joining forces to reduce the noise in the constraints library space, and to focus efforts and energy to try and build an extremely valuable constraints framework?

https://github.com/uptech/Constraid

**Comment by roberthein** [comment]
Hi Andrew, how would such a collaboration, that would work for you, look like?

**Comment by cyphactor** [comment]
@roberthein, well, what I am envisioning would be to collapse the code bases into one code base as probably a new major release. Combine the two core teams to make 1 core team. My company http://upte.ch is sponsoring my development time and another dev from my company on the project, so it would continue to do so. http://upte.ch would also host a slack channel for the core team so that we could easily communicate, or if we decided it made more sense to host a public Gitter channel for the core team we could do that.

In terms of process, I think people should raise questions and values with the core team and we could work together to weight the pros and cons and come to a good conclusions to make the framework better. It is very valuable in my eyes to have others interested in this space to help throw ideas back and forth to hopefully come out with the best ones.

Also, having the core team centralized would mean that we are focusing our combined effort on the code, documentation, branding, marketing, etc of the project. This is a big advantage in my mind because it means more eyes would be on all of these things and providing opinions, and value to help make sure this is going in the correct direction.

In terms of licensing Constraid is currently under MIT and it looks like TinyConstraints is as well so that shouldn't be much of a problem. My company UpTech Works, LLC would be open to a joint license where both UpTech Works, LLC and you would be on the copyright. Also, http://upte.ch would want to host the project on our GitHub account.

In terms of name. We aren't necessarily sold on Constraid, it was just a quick play of words on Constraint + Aid that I came up with so that I could start writing code. So, if you have strong opinions about TinyConstraints we would be open to using that name.

The above was kinda just a quick brain dump. So, I am sure there are things that I have missed. But, I hope it is a good start to a conversation and the details around doing something like this. Please don't hesitate to continue the question with any questions or thoughts that you may have.

**Comment by roberthein** [comment]
I think I would like to keep things as they are for now.
Thank you for your interest in my project!

**Comment by cyphactor** [comment]
Cool cool
