### ISSUE TITLE
Naming suggestion

### ISSUE THREAD

**Issue by iambatoan** [roberthein/TinyConstraints#82]
Hi thanks for a cool lib!
I just suggest that why don't we call the function like this: `view.tiny.center(in: superview)` or `view.tiny.edgesToSuperView()` instead of `view.center(in: superview)` or `view.edgesToSuperView()`? So that we dont need to remember the function name.
Thank you

**Comment by roberthein** [comment]
Hi @iambatoan! 
I did consider this, but I went with the tiniest version with the least amount of redundancy while maintaining readability. Although adding `.tiny` would help with code completion, I think it would make it less readable, add redundancy and make it less tiny.
