### ISSUE TITLE
Nested Stack View

### ISSUE THREAD

**Issue by jarvis-wu** [roberthein/TinyConstraints#87]
Hi, just wondering is there a way to use the stack() method for building nested stack views (i.e. stack of stack views)? Currently we can only put [UIView] as the parameter for the function so it won't work for [[UIView]] or more layers of nesting. Thanks!

**Comment by roberthein** [comment]
No I'm sorry this is currently not possible. But if you find a way to do this in a neat way, I would very much welcome a PR :)
